### ISSUE TITLE
docute init popup "Cannot GET /"

### ISSUE THREAD

**Issue by mynameismuse** [egoist/docute#103]
docute was installed by npm. Building project with docute-cli, but throwed out "cannot get /" error after turning on the local testing server. It only succeeded once after the installation and turned into this issue once after.

**Comment by kobocn** [comment]
me too, docute was installed by npm, follow the step, input docute-cli,"cannot get /" error after turning on the local testing server.

**Comment by egoist** [comment]
not sure what's going on here, the `docute` command by default serves `./docs` but you can change it `docute ./path/to/docs`.

In fact all kinds of static servers would work, like serve: `npm i -g serve && serve docs`

**Comment by geekxiaoyuchen** [comment]
found the problem. make sure you write the complete path of your project. for example, my doc root path is: ~/iCode/doc.xiaoyuchen.com, then you should use the command of: docute ~/iCode/doc.xiaoyuchen.com instead of docute doc.xiaoyuchen.com. hope helpful.

**Comment by egoist** [comment]
@geekxiaoyuchen relative path works too, just make sure the path is correct

**Comment by mynameismuse** [comment]
it works. @geekxiaoyuchen @egoist
