### ISSUE TITLE
Versioned docs

### ISSUE THREAD

**Issue by marvinroger** [egoist/docute#105]
There could be some sort of version picker that would show all available tags on the repo (with a regex pattern for example) and show the according docs. That would be great!

**Comment by egoist** [comment]
Does something like this work for you?

<img width="384" alt="2017-06-09 1 29 16" src="https://user-images.githubusercontent.com/8784712/26962275-b1416abe-4d17-11e7-93a7-261df64a2001.png">

http://vuejs.github.io/rollup-plugin-vue/#/en/2.3/

**Comment by marvinroger** [comment]
It would, but having to duplicate the previous docs just does not feel right! If you have a rather large docs with pictures, it would quickly fill up the git repo.

**Comment by egoist** [comment]
Hmm, I don't understand what you mean, I think docs for different versions can share assets like images

**Comment by marvinroger** [comment]
That's right, we can share the assets. But still, the markdown files would be duplicated, as we have to create a new folder each time we release a new version.

Here's how I envision it:

* Docute would fetch the list of tag for the repo: https://api.github.com/repos/egoist/docute/tags
* It would then show a picker with each tag corresponding to a regex pattern (semver for example)
* It would then fetch the corresponding files via GitHub, e.g. for v2.9.3: https://raw.githubusercontent.com/egoist/docute/v2.9.3/docs/README.md

It's just an idea, I understand if you would not want to go in that direction.

**Comment by egoist** [comment]
gotcha, that makes sense to me, I will try to implement this in the weekend

**Comment by ezra-obiwale** [comment]
Hey @egoist . Great job with Docute.

Just wondering if there's been any update on this?

Cheers.

**Comment by markadrake** [comment]
I'd like this functionality as well! @egoist have you made any progress on it? Do we agree on @marvinroger approach?

**Comment by egoist** [comment]
@markadrake not yet, but the`source` option could be a workaound https://docute.js.org/#/home?id=custom-source

**Comment by marvinroger** [comment]
Cleaning up my issues, and I see that this project is not maintained anymore, genuine thanks for all your awesome projects @egoist!
