### ISSUE TITLE
Can we customize the sidebar that using the files' name in an directory rather than the default action

### ISSUE THREAD

**Issue by toxichl** [egoist/docute#107]
This TOC of sidebar in the docs is described as follows:
```
The TOC is coming from your markdown files, we parse markdown content and get headings (h2 to h5+) to group a nested TOC.
```
So, If we want to customize the sider like this: to using all the directories' files as the TOC, how should we do? For this request is just due to in many conditions, I would need to write many separate MD files instead of writing a single file.

**Comment by toxichl** [comment]
Just like this snapshot:
![image](https://user-images.githubusercontent.com/23133919/27240888-12d28a14-5309-11e7-99b9-3f78098ab620.png)

It would be exciting to directly use the files' name as the sidebar's TOP level's name 😁

Maybe It can be a new feature, If `deal group owner` didn't have time, Maybe I can try to work for it 😅

**Comment by toxichl** [comment]
I have a good idea to solve this request ---- we can add a configuration for the spa:

Guarantee the order of the files though the config, and combined them during the compiled period

Still write different files, and actually still be compiled into a file

I don't know whether it is feasible.

**Comment by egoist** [comment]
Sounds like this? https://docute.js.org/#/home?id=custom-toc

**Comment by toxichl** [comment]
Nice, It's what I need, thanks.
