### ISSUE TITLE
Server-side rendering

### ISSUE THREAD

**Issue by egoist** [egoist/docute#12]
`docute` can be used alone as single page app but what if it supports SSR? If you care about SEO then SSR is a big win!

The further plan is to support generating static html files at some point.

Maybe it will be the first docs generator that supports:

- single page app, build docs on the fly
- server-side rendering, you don't need to build the docs but also have it seo-friendly
- build to static files, just like traditional static website generator

**Comment by egoist** [comment]
Actually these ideas are taken from @Atinux 's nuxt.js

**Comment by ipengyo** [comment]
请问一下 什么时候可以完工？

**Comment by egoist** [comment]
额，我推荐用 @nuxtjs

**Comment by ipengyo** [comment]
谢谢，请问一下这个东西如何与你的东西结合起来呢？

**Comment by ipengyo** [comment]
vue初学者 ···见谅！！！ 嘻嘻嘻

**Comment by javanigus** [comment]
Does this mean server-side rendering will not be added to Docute?

**Comment by egoist** [comment]
@javanigus there will be a rewrite so SSR will eventually come, I just don't have much time 😅

**Comment by egoist** [comment]
@javanigus there will be a rewrite so SSR will eventually come, I just don't have much time 😅

**Comment by niftylettuce** [comment]
please re-open

**Comment by niftylettuce** [comment]
bug bounty for you @egoist if you resolve 👍
