### ISSUE TITLE
How to point markdown urls to the correct docute generated path.

### ISSUE THREAD

**Issue by kudapara** [egoist/docute#126]
From the official docute documentation it is said
> You can also add more markdown files to display more pages. For example, adding chinese.md to your doc folder so that you got a new page at /#/chinese!
It supports directory too, just try adding a new file at language/chinese.md, then you'll get /#/language/chinese.
Note: file like about/README.md will be mapping to /#/about/, while the /#/about is for about.md.

I am working on a live book repository that has links to other markdown files within the repo. In the main README.md I have a link ```[Production Tips](/production/tips.md)```. I have only one problem with this. When docute generates the documentation the final url will be ```/production/tips``` instead of ```/production/tips.md``` . So when the user click on the link, it generates a 404.
I could rename the url in to ```[production tips](/production/tips)``` in the main README.md but this will break the code on github leading to dead links. Is there a way to configure docute to map the url to ```/production/tips.md```. Can someone help please

**Comment by egoist** [comment]
You can't have them both work at the same time 😄 you can choose either github or docute to display your docs.

**Comment by kudapara** [comment]
Thank you. Are there any plans to add that feature in the future?
