### ISSUE TITLE
FAQ: Why choose docute vs docsify?

### ISSUE THREAD

**Issue by shreeve** [egoist/docute#127]
I'm trying to determine the main difference between docute and docsify, but haven't been able to really see a side-by-side comparison.

Does such a comparison exist? If not, who could best supply one?

Thanks!

**Comment by wsd1** [comment]
After a day of checking, I choose docute, because it is structured totally in vuejs stack which I familiar with. I read over docsfys code, great ,learned a lot but i think I can not handle it in short time.

**Comment by egoist** [comment]
1. The architecture, we're Vue based and docsify is vanilla js based
2. UI
