### ISSUE TITLE
Proper url paths

### ISSUE THREAD

**Issue by ezra-obiwale** [egoist/docute#128]
For links like 
```
[Test Link](/test-link)
```
which resolve to 
```
<a href="/test-link" router-link="/test-link">Test Link</a>
```
, it would be great if the `href` attribute actually bears the proper url like `href="/#/test-link"`.

This is important for Algolia's bot when crawling the pages as the current link `/test-link` is of course broken.

This is currently affecting my [Laraquick](http://laraquick.ezraobiwale.com)'s doc.

**Comment by richardchien** [comment]
+1

Actually this willl also cause 404 when the user right clicks the link and opens in new tab, even affecting the official docs (the link with title _plugins_ in https://v3.docute.org/#/home?id=how-to-run-code-inside-markdown).

**Comment by sunk818** [comment]
Is there documentation on making this work with Apache and ModRewrite? The URL scheme is predictable so I think it wouldn't take much effort to rewrite and redirect the URLs in real-time. This, of course, means you'd need access to Apache web server and .htaccess .
