### ISSUE TITLE
Fetch API cannot load

### ISSUE THREAD

**Issue by jofralogo** [egoist/docute#129]
Hi everybody,

I really hope that docute could fit for me. For security reasons in my company I can't have a server to put the files (even plain html) so I have to make the docs work offline in a folder and distribute them in a zip file. It's ugly and shabby, I know, but it's better than the Powerpoint file that is the current solution...  

The problem is that I'm getting this error:

<img width="705" alt="captura de pantalla 2017-12-05 a las 9 33 17" src="https://user-images.githubusercontent.com/1077268/33597361-82c4a1e6-d99f-11e7-8ded-2ac789171233.png">

My docute.init is:
`
docute.init({
      url: '.'
    })
`
README.md exists in root directory and it works with an external url.

Is there any solution for this?

Thanks in advance

**Comment by egoist** [comment]
You can configure your server to use https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication

**Comment by jofralogo** [comment]
Thanks for your quick response @egoist but this doesn't solve my problem because I can't use a server.
I would want to distribute the docs in a zipped folder file to work offline: just opening the index.html with Chrome,  totally serverless. 

Is it feasible?

Thanks!

**Comment by egoist** [comment]
the web api cannot directly interact with your file system, you may use a static server to serve the files locally, for example using node.js:

```bash
npm i -g serve
serve [path/to/your/docs]
```
