### ISSUE TITLE
报错Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null

### ISSUE THREAD

**Issue by maojiudada** [egoist/docute#138]
我几个页面都在一个目录下，tbar上是页面所对应的路径，点击tbar上面的页面，页面会切换到对应的页面，sidebar跟页面内容都没问题。但是当我点击sidebar的锚点的时候，没反应，控制台报错`Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null`

**Comment by jamesmarva** [comment]
哥们你这个是咋个解决的？
