### ISSUE TITLE
4.0 Kick off 💫 

### ISSUE THREAD

**Issue by ulivz** [egoist/docute#143]
Since @egoist want to rewrite docute, It's time to kick off 4.0 ?

- [ ] Support PWA
- [ ] Support SSR
- [ ] Integrate code fragment to [codepan](https://github.com/egoist/codepan)?
- [ ] More friendly SEO
- [ ] More fancy welcome view page
- [ ] More themes
- [ ] Support for blog?
- [ ] Support CLI for scaffolding a Documentation or Blog template?
- [ ] Support CLI for generate config file by file tree?
- [ ] Use Typescript?
- [ ] Split plugins into multiple packages and use lerna?
....

Do not hesitate, just say what you think

**Comment by Itherael** [comment]
Support local search instead of algolia

**Comment by stasson** [comment]
Hello docute team, 

I'm just throwing ideas

Not sure about the blog. IMHO, focus should be on software documentation. what I'm looking for when using docute is a no brainer doc generation for my User Manual (Guide)  or Reference Manual (APIs)

Here couple of features I'd like 

- [ ] Guide or User Manual from doc tree markdown  (gitbook way or directly fetching README.md files from the source tree)
- [ ] Generate modules/components API Doc with props/methods extracted from JSDOC
- [ ] support static SPA build 
- [ ] support PDF build 
- [ ] support plugins for markdown pre-processing ( plantuml, ...)

**Comment by stasson** [comment]
- [ ] support plugin for [styleguidist](https://github.com/vue-styleguidist/vue-styleguidist)

**Comment by waruqi** [comment]
[ ] Sidebar directory navigation supports multiple markdown pages

**Comment by egoist** [comment]
lets use #112 instead.
