### ISSUE TITLE
Add an option to decide when to open externel links at new tabs?

### ISSUE THREAD

**Issue by richardchien** [egoist/docute#146]
The current behavior is to open externel links (path with full url) at new tabs, but sometimes I don't want this (e.g. a navbar item which links to a page relevant to the current page, and the user may not want to go back).

What about adding an option like this:

```js
nav: [
  { title: '首页', path: '/' },
  { title: '文档', path: window.location.href + 'docs/', targetBlank: false },
],
```

**Comment by egoist** [comment]
> a navbar item which links to a page relevant to the current page, and the user may not want to go back

That seems like a rare use case

**Comment by egoist** [comment]
Closing this since I'm not going to add new features to v3.x.

See https://github.com/egoist/docute/issues/208 for this feature in v4.

**Comment by egoist** [comment]
Closing this since I'm not going to add new features to v3.x.

See https://github.com/egoist/docute/issues/208 for this feature in v4.
