### ISSUE TITLE
Expose vue components for usage?

### ISSUE THREAD

**Issue by phillbaker** [egoist/docute#147]
Thanks for all the work you've put into this!

Similar to https://github.com/egoist/docute/issues/81, what do you think about exposing some of the Vue components themselves so that docute could be embedded in a larger application?

**Comment by egoist** [comment]
@phillbaker yep that is in the plan for docute 4

**Comment by phillbaker** [comment]
Awesome! Not sure I have much bandwidth to help out on development, but would certainly be willing to try out prototypes and beta test.

Will close for now as it seems it's already been discussed elsewhere.

**Comment by egoist** [comment]
For discussions on 4.0 design please go here #112, suggestions are always welcome.
