### ISSUE TITLE
如何添加侧边栏

### ISSUE THREAD

**Issue by Hishengs** [egoist/docute#15]
文档中好像没有关于如何添加侧边栏的说明？

**Comment by egoist** [comment]
侧边栏是从 markdown 文档里的 h2 ~ h5 标题自动生成的

**Comment by egoist** [comment]
添加了相关说明到[文档](https://docute.js.org/#/zh-Hans/?id=%E4%BE%A7%E8%BE%B9%E6%A0%8F%E6%98%AF%E4%BB%8E%E5%93%AA%E6%9D%A5%E7%9A%84)里
