### ISSUE TITLE
Mobile friendly docs

### ISSUE THREAD

**Issue by notoriousb1t** [egoist/docute#155]
I found your site through twitter and loaded the docs in mobile safari. You may want to consider collapsing the side nav and reducing fonts/whitespace for mobile.

![df0bd7dc-9160-483a-87fb-32ccd9c525f1](https://user-images.githubusercontent.com/736847/38164284-d116f96c-34cf-11e8-800d-544e1e061bc6.jpeg)

**Comment by ulivz** [comment]
Looks like it is duplicate to https://github.com/egoist/docute/issues/153.

**Comment by notoriousb1t** [comment]
I don't know what that means, but cool.  I just wanted to let you all know.

**Comment by egoist** [comment]
Thanks for your report 😄It's currently WIP so making it mobile-friendly is definitely on our todo list, will continue the work at #153
