### ISSUE TITLE
Disqus Plugin doesn't work

### ISSUE THREAD

**Issue by Genuifx** [egoist/docute#158]
I am writing doc with docute, while using disqus plugin for my site.
config like following: 
```js
   plugins: [
        evanyou(),
        disqus({
            shortname: 'wxa.disqus.com'
        })
    ]
```

while, dependencies like this: 
```html
  <script src="https://unpkg.com/docute-evanyou@0.4.0/dist/evanyou.min.js"></script>
  <script src="https://unpkg.com/docute/plugins/disqus.js"></script>
  <script src="https://unpkg.com/docute@2/dist/docute.js"></script>
```

but, It doesn't work at all. anything I need to do for this?

**Comment by Genuifx** [comment]
`
  <script src="https://cdn.jsdelivr.net/npm/docute/plugins/docsearch.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/docute/plugins/disqus.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/docute-evanyou/dist/evanyou.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/docute/dist/docute.js"></script>
`

oooo....ok, i fix this with this source.

**Comment by Genuifx** [comment]
why not update the docs and the scaffolding

**Comment by egoist** [comment]
Fixed in 3.4.11, jsdelivr might work because cache, something is broken in 3.4.10

**Comment by Genuifx** [comment]
tks, and if there any docute's plugin support emoji? @egoist

**Comment by egoist** [comment]
what do you mean? you can use emoji in markdown file

**Comment by Genuifx** [comment]
oops, I just use github provided emoji, like :100:

**Comment by egoist** [comment]
@Genuifx got you covered: https://github.com/hkwu/docute-emojify

**Comment by Genuifx** [comment]
tks
