### ISSUE TITLE
How can I export static sites and build github pages?

### ISSUE THREAD

**Issue by itfanr** [egoist/docute#160]

**Comment by savokiss** [comment]
u can see my repo: https://github.com/savokiss/docs

just set master branch as github pages in setting~

**Comment by itfanr** [comment]
@savokiss 
So cool!
But your repo is not exported by docute .  Is is written by youself ?

**Comment by itfanr** [comment]
@savokiss 
I found this : 
```
 <script src="https://unpkg.com/docute/dist/docute.js"></script>
```
👍

**Comment by savokiss** [comment]
Glad to see, u can close this issue now~😊
