### ISSUE TITLE
Search UI need to be updated

### ISSUE THREAD

**Issue by s-pace** [egoist/docute#163]
👋 @egoist,

I am working on DocSearch and I have updated [your configuration in order to handle your new URLs.](https://github.com/algolia/docsearch-configs/commit/45d4892b4457accff4f3352e48315bd35cedf794)

Given that your search UI is replacing some part of URL and that the URL aren't the same anymore, your index is updated from your website content but the search is broken:

![Search broken](https://user-images.githubusercontent.com/32097720/38617115-7901b044-3d96-11e8-8442-13077921d233.png)

If you want to do a quick fix, I have updated [`docute`](https://github.com/algolia/docsearch-configs/blob/master/configs/docute.json). It is deploy and contains the newest content.

Last but not least, your `lvl0` & `lvl1` selectors were equals. This is something useless that we want to avoid because it is redundant. I have bootstrap you an temporary index (indexName:`docute_new_tmp`, apiKey:`a2bc5916c5c9a843db38ecad43eb67dd`) and [a playground](http://jsfiddle.net/s_pace/La0gh9qy/). 

If you do some test with `docute_new_tmp`. Please ping me once you are done, I will populate `docute_new_tmp` into `docute`

Cheers

**Comment by egoist** [comment]
oh thanks for letting me know, will update it soon.

**Comment by egoist** [comment]
Seems to be working fine for me.

**Comment by s-pace** [comment]
On https://v3.docute.org/?

**Comment by egoist** [comment]
I tested it locally with `docute_new_tmp`

**Comment by s-pace** [comment]
Alright, I don't have the issue anymore.

I have still upgrade your search since we weren't scraping you cli and plugin section from the english pages.

[Changes are here](https://github.com/algolia/docsearch-configs/commit/8943e8c105143cdca7947960eba3f9994ed2df3a)

If `docute_new_tmp ` works fine for you, let me know and I will override the `docute` one with it.

**Comment by egoist** [comment]
Yeah I think that's working 👌

**Comment by s-pace** [comment]
👍 Change made and new index deployed. Changes are live
