### ISSUE TITLE
How can I add custom plugins?

### ISSUE THREAD

**Issue by waruqi** [egoist/docute#164]
我想添加一个第三方的评论系统，我看到config.js 里面可以配置插件，我问下自己如何扩展添加一个类似docsearch的插件呢？

是必须要修改源码吗，还是config.js里面就可以配置？

```js
  plugins: [
    docsearch({
    }),

    myplugin({
    })
  ]
```

**Comment by egoist** [comment]
https://v3.docute.org/#/plugins?id=write-a-plugin

https://github.com/egoist/docute/blob/3/src/plugins/disqus/index.js

**Comment by waruqi** [comment]
谢谢，我试试！

**Comment by waruqi** [comment]
可以了 谢谢！
