### ISSUE TITLE
Search in docs

### ISSUE THREAD

**Issue by egoist** [egoist/docute#17]
Currently there's no universal way to search a keyword in markdown files, the last option I can think of is to generate a json file for these files for searching 🤔 but um.. you need to **generate** each time after you updated the docs ...

**Comment by egoist** [comment]
The other option is server-side rendering and with the help from google or algolia.com

**Comment by egoist** [comment]
I guess algolia.com docsearch does support SPA! https://github.com/algolia/docsearch-scraper/pull/46

**Comment by egoist** [comment]
This is done, furthur work goes to https://github.com/egoist/docute/issues/21

**Comment by znck** [comment]
There is some issue with search result routing. 

Quick Repro: Visit http://vuejs.github.io/rollup-plugin-vue/#/en/2.3/?keyword=style and  click on any result item.

**Comment by egoist** [comment]
@znck seems using regexp [here](https://github.com/algolia/docsearch-configs/blob/c72ff3caa67fe50b32607fd573b992e0b4adeddb/configs/rollup-plugin-vue.json#L5) will make it return full path including domain?

**Comment by egoist** [comment]
oh, I forgot that, you should set `$config.url` to the url of the doc

**Comment by znck** [comment]
Oh! Sorry! Missed that.

I should set `url` to `https://vuejs.github.io/rollup-plugin-vue`. Right?

**Comment by egoist** [comment]
@znck yep
