### ISSUE TITLE
Feature: Dark mode

### ISSUE THREAD

**Issue by imsus** [egoist/docute#189]
I think it's better to have a button to switch between light/dark mode for default theme.

And further we can customize the css for dark mode itself.

**Comment by egoist** [comment]
I'd like to have a dark theme first, starting by exposing more CSS variables 🤔

**Comment by dobromir-hristov** [comment]
I am up for expanding the current theme with more variables and stuff. Do you guys have a nice example of a dark theme that I could "borrow" colors from lol. 

How would you like to have the dark theme, by adding a class to the body, for example, that would switch the css vars?

**Comment by egoist** [comment]
@dobromir-hristov the only one that came to my mind is https://hyper.is/

> How would you like to have the dark theme, by adding a class to the body, for example, that would switch the css vars?

LGTM. we can add the classname to [root component](https://github.com/leptosia/docute/blob/master/src/components/Root.vue) instead and let use configure it via `theme: 'dark'` option.

**Comment by dobromir-hristov** [comment]
And we get the provided option from vuex? OK, should work, will try to prep something these days.

**Comment by egoist** [comment]
4.11.1 added dark [theme](https://docute.org/options#theme) support: 

![屏幕快照 2019-03-23 上午1 43 47](https://user-images.githubusercontent.com/8784712/54842596-42138580-4d0d-11e9-9722-2e4165876ed1.png)

More css variables are exposed as well: https://docute.org/guide/customization#custom-style

**Comment by dobromir-hristov** [comment]
Hah, the way you implemented it is super clever, nice one :)

**Comment by egoist** [comment]
Closing as it's resolved :)
