### ISSUE TITLE
Optimization for wide screens

### ISSUE THREAD

**Issue by idiotWu** [egoist/docute#19]
In current layouts, contents will take up as much space as they can. On my 1080p monitor, it's a bit hard to read text from leftmost to rightmost. What about adding a `max-width` property to contents and align them in the center?

![screenshot](https://cloud.githubusercontent.com/assets/6022672/21270502/49f3b6a6-c3fa-11e6-9f5e-40ad1971ff30.png)

**Comment by egoist** [comment]
Yeah, that makes sense. I didn't even notice this because I'm using a small laptop 😂

**Comment by egoist** [comment]
Currently `v1.0.0` the main content is limited to 900px and being centered, the sidebar is `fixed` element, so still on the leftmost side.

**Comment by idiotWu** [comment]
@egoist new layout is buggy 😂

![screenshot](https://cloud.githubusercontent.com/assets/6022672/21314643/7bcd769c-c63b-11e6-86be-4661820ff164.png)

I think you'd better not change

```css
.main {
  padding-left: 280px;
}
```

to

```css
.main {
  margin-left: 280px;
}
```

`margin-left` is overwritten by `margin: 0 auto` when centering contents.

**Comment by egoist** [comment]
It should be fixed now, but sadly I have no device to test 😂

**Comment by idiotWu** [comment]
Well, now it's a little too narrow...

Actually, you can use the responsive design tool to 'resize' your layout to larger dimensions. But I think I should create a PR for this issue 😂

**Comment by egoist** [comment]
just forgot about that... I've fixed this a bit, any PR to improve it is welcome ;)
