### ISSUE TITLE
can't jump to encoded character hash

### ISSUE THREAD

**Issue by baram204** [egoist/docute#212]
I clicked `[sidebar](./options#사이드바)` hash link.

but, url link encoded. 

<a href="/kr/options#%EC%82%AC%EC%9D%B4%EB%93%9C%EB%B0%94" class="">sidebar</a>

so I Got result below.

```
×
Unhandled Rejection (SyntaxError): Failed to execute 'querySelector' on 'Document': '#%EC%82%AC%EC%9D%B4%EB%93%9C%EB%B0%94' is not a valid selector.
VueComponent.jumpToHash
```

so, I edit jumpToHash() to get Decoded string.

```js
    jumpToHash() {
      const {hash} = decodeURI(this.$route)
      if (hash) {
```

now, no more `'9C%EB%B0%94' is not a valid selector`. but still It's not jump to hash position.

I think that jump.js can't recognize hash position.

**Comment by egoist** [comment]
Yeah we need to `decodeURIComponent`, PR welcome.

**Comment by baram204** [comment]
ah-ha.
`const hash = decodeURI(this.$route.hash)` works. 

I'll PR soon. Thanks to make this nice program!
