### ISSUE TITLE
2 different website URLs

### ISSUE THREAD

**Issue by Sajo8** [egoist/docute#229]
![a](https://i.imgur.com/9gUwvUy.png)
and
![b](https://i.imgur.com/6aFcGF0.png)
show two different website URLs; the content appears to be the same, however. I guess you have to replace the first one with docute.org?

**Comment by egoist** [comment]
Fixed, thanks for reporting.

**Comment by egoist** [comment]
Fixed, thanks for reporting.

Sajo8 <notifications@github.com> 于 2019年5月31日周五 上午5:09写道：
