### ISSUE TITLE
JAM stack

### ISSUE THREAD

**Issue by janat08** [egoist/docute#240]
I'm not familiar with the 'stack'. The gist of it is you build spa, and then convert it back to html for the purposes of the faster first load. https://gridsome.org/docs/jamstack

**Comment by egoist** [comment]
You mean you want to fetch data from external resources? Use this option then: https://docute.org/options#routes

**Comment by janat08** [comment]
I was suggesting that some amount of integration with markdown generator (which is suppose to produce html at build time) would be beneficial since you get CDN/SEO out of it, or you could just leave it to users.

**Comment by egoist** [comment]
> produce html at build time

that's actually what this project is trying to avoid..
