### ISSUE TITLE
markdown-it

### ISSUE THREAD

**Issue by berot3** [egoist/docute#254]
Is it possible to use [markdown-it](https://github.com/markdown-it/markdown-it) and [all its available pugins](https://www.npmjs.com/search?q=keywords%3Amarkdown-it-plugin&ranking=popularity)?

Are you maybe already working on it? https://github.com/egoist/docute-markdown-it
I could not find any documentation regarding this.

**Comment by egoist** [comment]
There's no plan to support markdown-it or other markdown parser, but there's a plugin API (https://docute.org/plugin-api#apiprocesshtmlfn) which you can use to transform the HTML.
