### ISSUE TITLE
Update sidebar UI

### ISSUE THREAD

**Issue by egoist** [egoist/docute#256]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24100%20Funded-%2300A156.svg" />](https://issuehunt.io/r/egoist/docute/issues/256)

Update the sidebar UI to match https://zeit.co/docs

The new `sidebar` option:

```ts
type Sidebar = Array<SingleItem|MultiItem>

interface SingleItem {
  title: string
  link: string
  // For external links
  openInNewTab?: boolean
}

interface MultiItem {
  title: string
  children: Array<SingleItem>
  expanded?: boolean
}
```

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $100.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($100.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/egoist/docute/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by saltysugar** [comment]
I’ll give it a shot.
