### ISSUE TITLE
[feature request]cover/landing page support

### ISSUE THREAD

**Issue by idiotWu** [egoist/docute#29]
Noticed that cover pages have been supported by [docsify](https://github.com/QingWei-Li/docsify) since a recent update (well, I don't know the exact version...). As most open source projects are serving an appealing landing page,  I think it would be great if we could also create a cover or landing page for docute :)

**Comment by egoist** [comment]
Yep, that would be fancy, but directly showing a landing page upon the main content looks too ugly.

**Comment by egoist** [comment]
my idea is:

```js
self.$config = {
  landing: 'landing.md' // or true
}
```

when landing is set the `/` will give you a landing page, and the `/home` will be the homepage of your doc

**Comment by idiotWu** [comment]
@egoist yeah, I was thinking about this before but couldn't get an answer to it. The layout of docsify will also cause it hard to serve a multi-page documentation 😢.

I've also thought about the additional `landing.md` solution, but it seems to be painful to code a fancy page inside markdown 🤣 

Will it be possible to support a HTML document as landing page?

**Comment by egoist** [comment]
The markdown file already supports HTML and CSS

**Comment by idiotWu** [comment]
But it's so wired to write nothing but markups in a `I-AM-MARKDOWN.md` file.

**Comment by egoist** [comment]
`.html` file would work too, and we can skip parsing it using marked in that case.

btw we can provide some basic layout options if user chooses to use markdown:

```
---
layout: clickbait
logo: ./a.png
---
- feature a
- feature b
```

**Comment by idiotWu** [comment]
Hmmm...that sounds good to me.

One more thing: supposing that we support landing page, should we add a link on the top of sidebar (or wherever) to navigate back to the landing page? Because at that time landing page is regarded as the home page.

**Comment by egoist** [comment]
maybe an icon next to the `sidebar toggle` icon

**Comment by egoist** [comment]
We need to figure out a good way to setting routes when `landing` is enable, so far we know:

`/` would be the route for landing page, so for docs should we prefix all routes with `/docs` or just change the homepage of docs to `/docs`?

**Comment by egoist** [comment]
OK, my final solution is change the route for doc's homepage to `/home`, and `/` is reserved for landing page.

**Comment by egoist** [comment]
The landing page is pretty much done, check out https://docute.js.org
