### ISSUE TITLE
想了解一下关于搜索这一块

### ISSUE THREAD

**Issue by henryzp** [egoist/docute#32]
这个地址：`https://docute.js.org/#/home`

左上角有搜索框，想了解它的具体点实现？

比如说应该怎么配置，才能出来？

另外想了解的是如果是多个md的话，这个搜索，会不会针对所有的md进行搜索，还是针对当前的md进行搜索？

**Comment by egoist** [comment]
文档里用的 [docsearch](https://docute.js.org/#/zh-Hans/plugins?id=docsearch) 这个插件，它会默认搜索所有抓取的页面，不过也可以用 front-matter 指定只搜索某些 tag

不过类似这个插件，你可以把 markdown 文件按关键词编译成 json 文件用于搜索，也就是计划中的这个[localsearch 插件](https://github.com/egoist/docute/issues/21) 😅

**Comment by henryzp** [comment]
按关键词编译成json，这个我觉得一般需求不是太大吧？

一般搜索都是扫全局的md文章里面的内容。。想想，这两个配合着用的话，倒是有一定的需求。

**Comment by egoist** [comment]
我搞错了，不过按关键词编译成 json，只需要按关键词搜索就行了。

**Comment by henryzp** [comment]
那你是准备把这两个插件整合在一起吗？

还是单独用？

感觉两个都有点需求。。但全局搜，可能需求会大一些，不过查询的时间可能也会长一些，相对于根据key来找对应的md。。。

**Comment by egoist** [comment]
当然是两个插件。查询不会慢啊，都已经全编译到一个 json 文件里了，只是那个 json 文件会比较大。

**Comment by henryzp** [comment]
gitbook的搜索，目前是一个大坑。。它的中文搜索是从前匹配的，然后中间搜索根本就不行。。

后来让我找到这个`https://github.com/codepiano/gitbook`

在mac下可以，但在linux下会报错。。

所以搜索这个功能，我还是在乎的。。

**Comment by egoist** [comment]
其实怎样搜索都可以，你可以参考 https://github.com/egoist/docute/blob/master/src/plugins/docsearch.js

**Comment by henryzp** [comment]
@egoist ，嗯嗯。。
