### ISSUE TITLE
Access Vue Variable on plugin

### ISSUE THREAD

**Issue by diruuu** [egoist/docute#38]
I want to create a plugin, but to create a plugin, I need to register a component first. Unfortunately I cannot create a Vue component because I can't access Vue variable from config.js where we usually init a plugin. The config.js is located before the docute js file.

Please help me on this.

**Comment by egoist** [comment]
Why do you want to register component?

**Comment by diruuu** [comment]
Because the documentation says the plugins context has `registerComponent` which accept Vue component as the argument. I want to append the component at the end of docute content. So the question is, how do I create the Vue component if I cannot access the global Vue variable on the plugin?

**Comment by egoist** [comment]
You don't need `Vue`, simply:

```js
registerComponent('content:end', {
  render(h) {
    return h('div')
  }
})
```

**Comment by diruuu** [comment]
Great! I'll close this issue. Thanks man

**Comment by egoist** [comment]
btw, I just added `Vue` to context too in `v1.6.3` 😃

**Comment by diruuu** [comment]
Man, that's even great, thanks a lot. I admire your work.
