### ISSUE TITLE
Cannot Put Remote URL On Navbar

### ISSUE THREAD

**Issue by diruuu** [egoist/docute#41]
Is there any way I can do this on config file?
```js
nav: {
    default: [{
       title: 'Documentation', 
       path: 'https://raw.githubusercontent.com/ctrlplusb/react-universally/master/docs/NPMCommands.md'
     }]
  }
```

Where the path is remote URL instead of local markdown. I tried but it cannot load the markdown.

**Comment by egoist** [comment]
eh currently it does not support this. And I think `path` should always be a relative url to your website. for example `/foo` we fetch `/foo.md`, maybe we can add a `source` to fetch from a custom url.

**Comment by diruuu** [comment]
That would be great, man. I'm looking forward for that on the next version. :)

**Comment by egoist** [comment]
`v1.8.0` implements external url for `path` option

And `source` is also added for fetching from custom path, like `http://xxx.com/a.md` or `/foo.md`, all relative path (without `https?://`) will be suffixed with a `.md` extension.

**Comment by egoist** [comment]
well it turns out the `source` option is quite useful, I've used it in [one of my projects](https://github.com/egoist/sao/blob/master/docs/config.js#L6)! thanks for the inspiration 😎
