### ISSUE TITLE
suggestion: set default dropdown item

### ISSUE THREAD

**Issue by airyland** [egoist/docute#44]
I need to set a dropdown like this

```
- All Components  `/components`
- Form Components `/components_form`
- layout Components `/components_layout`
```

when users click the dropdown, it goes to `/components` without selecting.
And when users select `Form Component`, the dropdown title should be changed to `Form Components`.

Now it seems impossible to do this.

**Comment by egoist** [comment]
> when users click the dropdown, it goes to /components without selecting.

then users can never select items from dropdown menu if they're on mobile device. I'm not going to add this, but PR is welcome

> the dropdown title should be changed to Form Components.

Supported in `v1.10.0` by adding `exact` option, check out https://docute.js.org/#/home?id=exact
