### ISSUE TITLE
[Bug] dropdown menu navigation doesn't work in iPad landscape mode

### ISSUE THREAD

**Issue by Async0x42** [egoist/docute#45]
When viewing the docute documentation on a 9.7" iPad Pro in landscape mode, the dropdown navigation doesn't work. I'm only able to access the 'Languages' dropdown if I use Portrait mode with the pull-out menu.

**Comment by egoist** [comment]
eh, it works in chrome's device devtool, but I don't have an iPad to test real devices, maybe adding `onClick="return true"` could fix this.
