### ISSUE TITLE
Support history mode

### ISSUE THREAD

**Issue by egoist** [egoist/docute#49]
If you're using github pages, you can use `404.html` together with `index.html` to simulate a history-mode app (redirect 404.html to index.html), what we need to change is to make docute update `location.hash` instead `query.id` in history mode

**Comment by shershen08** [comment]
so this type of setting - redirect 404.html to index.html and enable history in router settings should only run for actual docute apps deployed to github pages only, right? 
can` location.hostname == "github.io"` be used for this, or I am missing smth?
