### ISSUE TITLE
put routers  at left instead

### ISSUE THREAD

**Issue by itfanr** [egoist/docute#50]
目前的docute是只能把导航栏放在顶部，而左侧的导航栏只能导航一个MD文件的标题。

但是，有很多情况下，是MD文件较多，需要把路由放在左侧能更加方便（忽略MD页面内部导航）。比如：http://ionicframework.com/docs/ 

请问这种情况下，我该怎么使用docute？谢谢。

**Comment by egoist** [comment]
可以写个组件用 [registerComponent](https://docute.js.org/#/plugins?id=registercomponent) 插入到 sidebar 同时把  toc 和 nav 关闭

**Comment by itfanr** [comment]
@egoist  好的。非常感谢！这么快就回复了。

**Comment by itfanr** [comment]
@egoist   我看很多文档，都是左侧导航条，有些是只有路由，有些是带有TOC。而顶部，放置一些官网、github等链接。

个人感觉这种方式更好些。嘿嘿。

**Comment by egoist** [comment]
这本来只是给只有个 README 的项目用的，可以做个插件通过 : `sidebarNav(nav)` 这样达到那种效果

**Comment by itfanr** [comment]
可惜我前端刚入门。我是c系列的。
