### ISSUE TITLE
[bug] scrolling inspector of sidebar mismatches

### ISSUE THREAD

**Issue by idiotWu** [egoist/docute#52]
![screenshot](https://cloud.githubusercontent.com/assets/6022672/21961982/874dd93c-db5b-11e6-8a2a-66deeab1cd2e.png)

As the screenshot shows, scrolling inspector of sidebar is somehow mismatching the `scrollTop` of document.

**Comment by idiotWu** [comment]
I have taken a glance at source code and felt confused with the`firstPositive.top > 200` statement [here](https://github.com/egoist/docute/blob/master/src/components/App.vue#L42). Thought it could work well without this statement as:

```js
if (lastNegative) {
  el = lastNegative
} else if (firstPositive) {
  el = firstPositive
} else {
  el = els[els.length - 1]
}
```

**Comment by egoist** [comment]
> felt confused with thefirstPositive.top > 200 statement 

```
lastNegative
---window top line---
|
| --> n px
|
firstPositive
---window bottom line---
```
 In such case, the active section might be `lastNegative` or `firstPositive`, the `firstPositive` is treated as active section only if its scrollTop is less than `200px`

> As for mobile devices? Ah, I think no one will scroll the main contents with sidebar opened

the `60px` is preserved for the space of `mobileHeader`, when you click some heading in the sidebar toc, it should scroll to relevant heading in main content anyways.

**Comment by idiotWu** [comment]
Yeah I knew the `60px` for mobiles. But I think it's not necessary to preserve `200px` for active section detection. As long as `lastNegative` exists, it ought to be the active section.

```
|- section-1: last negative
---window top---
|
|- seciton-2: first positive
|
---window bottom---

scroll =>

|- section-2: last negative
---window top---
|
|- seciton-3: first positive
|
---window bottom---
```

On this condition, `firstPositive` will only be treated as the active section when it across window top line (i.e. it turns into `lastNegative`).

**Comment by egoist** [comment]
> As long as lastNegative exists, it ought to be the active section.

um, what if the last section is very long and only several pixels left in viewport? 🤔 wouldn't the next section being treated as active section sound more reasonable?

**Comment by idiotWu** [comment]
But you see: when you click on a sidebar item, the page will scroll to the very beginning of target section - it somehow indicates that "a section is activated when it reaches the very top".

> what if the last section is very long and only several pixels left in viewport

Well, for a counter example, what if the last section is so short that it turns into inactive while there're still 90% of it are visible?

**Comment by idiotWu** [comment]
Since it seems we will never reach a consensus on this issue, I'm going to close it 🙃
