### ISSUE TITLE
The readability of highlight.js is really bad

### ISSUE THREAD

**Issue by idiotWu** [egoist/docute#53]
Sorry for bothering again 😂. As you can see from the screenshot below, the syntax highlight of [highlight.js](https://highlightjs.org) is really hard to read, it seems almost everything is black and thus messing up:

![screenshot](https://cloud.githubusercontent.com/assets/6022672/21987801/3d27587c-dc48-11e6-9095-927271eb6b05.png)

Since this is an internal module, I could not modify it 😢. Would you mind switching to the other plugins like the old [Prism.js](http://prismjs.com/)?

**Comment by egoist** [comment]
I'm open to switch language highlighter, maybe use Prism by default and expose `highlight(str, lang)` function in config file.

**Comment by egoist** [comment]
`v2.0` is using Prism.js now

**Comment by idiotWu** [comment]
Great! Much thanks!

**Comment by hackjutsu** [comment]
@idiotWu I'm interested in this topic. Can you paste a screenshot for the same snippet to illustarate how Prism.js improves the syntax highlighting?

**Comment by egoist** [comment]
@hackjutsu you can actually try this youself 😅

**Comment by idiotWu** [comment]
@hackjutsu the same code block with Prism.js:

![screenshot](https://cloud.githubusercontent.com/assets/6022672/22624202/55ec6af4-ebb7-11e6-9eee-103d3197eeb5.png)

And if you inspect the rendered result in dev tools, you will find the AST in Prism is much more detailed than that in highlight.js. If you are focusing on speed and performance, maybe highlight.js is a good choice :)

**Comment by hackjutsu** [comment]
@idiotWu That's cool. Thanks!
