### ISSUE TITLE
[bug] Warning CSS is above dropdown menu

### ISSUE THREAD

**Issue by Async0x42** [egoist/docute#56]
The dropdown menu seems to be underneath tip/warning css

![image](https://cloud.githubusercontent.com/assets/3268854/22180561/29b1886a-e041-11e6-905f-f72a86d9917e.png)

**Comment by egoist** [comment]
guess we need to add `z-index` to dropdown menu

**Comment by egoist** [comment]
Fixed in `v2.3.3`
