### ISSUE TITLE
How to add pagination?

### ISSUE THREAD

**Issue by ChangJoo-Park** [egoist/docute#58]
**docute** is very cute 👻 . It is awesome documentation tool. but Where can I find pagination?

**Comment by egoist** [comment]
We don't have a **list** here so why do you need pagination ?

**Comment by ChangJoo-Park** [comment]
I want to write long series of Vue.js tutorial like an [ember.js tutorial](https://guides.emberjs.com/v2.10.0/tutorial/ember-cli/).

Is the purpose of **docute** only single page document?

**Comment by egoist** [comment]
we don't really need that, if you mean something like `prev` and `next`. since all sections are in the same page, you can just scroll down to reach next section.

**Comment by ChangJoo-Park** [comment]
I agree your opinion :) Thank you for your work.

**Comment by egoist** [comment]
I'm going to add a gitbook-like mode https://github.com/egoist/docute/issues/59, then we'll also release a plugin that displays a pagination for you.
