### ISSUE TITLE
[question] Living component guide

### ISSUE THREAD

**Issue by ricardocasares** [egoist/docute#61]
Hi there, thanks to put this together, docute is really awesome.

I'd like to create a living component like style guide, showing different states of some components, also show some tabbed content, like `preview` and `source code` (maybe some markdown plugin to show tabs?).

Is this some how supported by docute? If so, what would be the best approach to author such style guide using docute?

Thanks!

**Comment by egoist** [comment]
maybe use codepen or jsbin?

If you're going for specific framework, you can use react-styleguidist or such?

**Comment by ricardocasares** [comment]
For now codepen is not an option since the project I'm working on it's not open source (yet), but will keep investigating on this.

Thanks!
