### ISSUE TITLE
关于docsearch问题

### ISSUE THREAD

**Issue by waruqi** [egoist/docute#62]
我参照文档，也申请了个docsearch，并且参照docute.json做了些修改：

https://github.com/algolia/docsearch-configs/blob/master/configs/xmake.json

appkey和tags都加上了，但是还是搜索不出来：

```js
 plugins: [
    docsearch({
      apiKey: 'fbba61eefc60a833d8caf1fa72bd8ef8',
      indexName: 'xmake',
      tags: ['en', 'zh']
    })
  ]
```

是我config.js配置的不对吗？还是xmake.json配置问题？文档地址：[http://xmake.io/#/home](http://xmake.io/#/home)

谢谢！

**Comment by egoist** [comment]
可能需要等一天才会抓取你的文档内容。

**Comment by waruqi** [comment]
好的 ，我再等会看看

谢谢

**Comment by waruqi** [comment]
中文的可以了，英文的可能我配置的还不对，我再研究下

谢谢哈

**Comment by waruqi** [comment]
你好

我参考`docute`的`config.js`配置，在自己的文档`config.js`配置了两个docsearch的tags，其中英文的tags，我改成了`en`，并且把`docseach-configs`里面的tag也改成了`en`：

```js
plugins: [
    docsearch({
      apiKey: 'fbba61eefc60a833d8caf1fa72bd8ef8',
      indexName: 'xmake',
      tags: ['en', 'zh']
    })
  ]
```

然后抓包发现，请求过去的还是 `tags: english`

```
{"requests":[{"indexName":"xmake","params":"query:Installation
filters:(tags:english)"}]}
```

我问下config.js里面改成`tags: ['en', 'zh']`支持吗？ 还是英文搜索必须要`tags: ['english', 'zh']` 才行？

**Comment by egoist** [comment]
用你 xmake.json 里配置的 tag 就行，所以这里 https://github.com/tboox/xmake/blame/master/docs/README.md#L2 应该是用 `en`

**Comment by waruqi** [comment]
哦哦 了解了

谢谢。
