### ISSUE TITLE
how to use docute with pm2?

### ISSUE THREAD

**Issue by abnerCrack** [egoist/docute#63]
RT.

**Comment by egoist** [comment]
your docute website contains only static files, so using a static web server is enough.

**Comment by abnerCrack** [comment]
but i want to keep the live load.

**Comment by egoist** [comment]
I guess you mean docute-cli?

**Comment by abnerCrack** [comment]
这个不支持后台重载吧。需要自己手动写脚本实现吧。刚才看了help信息。

**Comment by egoist** [comment]
`docute --watch`

**Comment by abnerCrack** [comment]
我知道这个。但是这个要开着shell，我想让他后台运行。。我写个nodejs脚本得了。。不麻烦了。

**Comment by abnerCrack** [comment]
感谢回复。
