### ISSUE TITLE
Can fix navbar at top?

### ISSUE THREAD

**Issue by leitwolf** [egoist/docute#70]
Please add this feature. Thank you!

**Comment by egoist** [comment]
This feature is enabled by default in `v2.6` and beyond.

**Comment by leitwolf** [comment]
Not perfect when hide sidebar.
![sqvtrbl q ziv3gid1dl6c](https://cloud.githubusercontent.com/assets/1720546/23587074/f3e75ab0-01de-11e7-9fb8-7a8850071514.png)

**Comment by egoist** [comment]
@leitwolf nice catch, fixed in a new release.
