### ISSUE TITLE
Feature: Allow full customization for icons

### ISSUE THREAD

**Issue by phanan** [egoist/docute#72]
Currently, users can only specify the icons this way:

```js
repo: 'egoist/docute',
twitter: 'rem_rin_rin'
```

The rest of the information is being hardcoded in `Home.vue`. We can take this one step further by allowing the value to be full objects:

```js
repo: {
  link: 'egoist/docute',
  label: 'Contribute on GitHub',
  icon: 'edit' // notice, I'm suggesting using "icon" instead of "svg" as the key
}
```

To maintain backward compatibility, we can check the value's type. If it's a string, keep the current behavior. If it's an object, merge it with the default config before do a `defaultIcons.push()`. This will allow more flexibility.

If you're OK with this request, I can try creating a PR.

**Comment by egoist** [comment]
looking good to me, btw, it's even better if it supports using `https?://...` as the link

**Comment by egoist** [comment]
So do you think we should use `icon` here too? https://docute.js.org/#/home?id=custom-icons

**Comment by phanan** [comment]
I don't have a strong opinion about the latter, mostly because I've never used this feature.

**Comment by egoist** [comment]
Currently you can use custom icons like this to achieve the same thing:

```js
icons: [
    {
      label: 'Contribute on GitHub',
      link: 'https://github.com/owner/repo',
      svg: 'github'
    }
 ]
```

[Here's the list of built-in icon support](/src/components/SvgIcon.js)

So I guess we only need to change `svg` to `icon` to be more semantic.

**Comment by phanan** [comment]
Oh, that's right.
