### ISSUE TITLE
Inconsistent hidden state of sidebar

### ISSUE THREAD

**Issue by idiotWu** [egoist/docute#74]
## Steps to Repro

1. Hide sidebar
2. Switch to another page

![kapture 2017-03-08 at 14 37 03](https://cloud.githubusercontent.com/assets/6022672/23691610/d444fbe2-040c-11e7-8d4a-f5428ff697d1.gif)

**Comment by egoist** [comment]
Hmm, this was a designed to be `hide temporarily`, but now I guess it's wrong 😄
