### ISSUE TITLE
Builtin support for scripts in Markdown

### ISSUE THREAD

**Issue by znck** [egoist/docute#75]
Vue components docs often require demos.

For example: https://vuejs.org/v2/guide/ all examples are rendered.

**Comment by egoist** [comment]
The only solution I have is https://docute.js.org/#/home?id=how-to-evaluate-script-tag-inside-markdown

Any good ideas?

**Comment by znck** [comment]
Add iframes!

```
<!--docute:raw-->
...
<!--docute:endraw-->
```

```
<iframe sandbox srcdoc="{{ content }}"></iframe>
```

**Comment by znck** [comment]
This is resolved with https://github.com/egoist/docute-iframe.
