### ISSUE TITLE
目录本地跳转的时候会自动编码  chrome不识别

### ISSUE THREAD

**Issue by abnerCrack** [egoist/docute#86]
触发条件:
2. [本次接口](/#/interface/2017-03-14)
mac chrome 转码之后就跪了。
但是github就没事

**Comment by egoist** [comment]
你发的链接是啥

**Comment by abnerCrack** [comment]
这个  ![image](https://cloud.githubusercontent.com/assets/8336662/24244766/34e1b9f0-0ffb-11e7-90c9-ec9c2ca2ae62.png)

**Comment by abnerCrack** [comment]
![image](https://cloud.githubusercontent.com/assets/8336662/24244792/54d04efc-0ffb-11e7-8bcf-962bd683b15e.png)
![image](https://cloud.githubusercontent.com/assets/8336662/24244803/5d3590a2-0ffb-11e7-818e-9c8b79569d01.png)

**Comment by egoist** [comment]
看不懂 😂 发个 repro 吧

**Comment by egoist** [comment]
不用加 `/#`

**Comment by abnerCrack** [comment]
TOT果然- - ，智商拙计、 多谢
