### ISSUE TITLE
Edit link to GitHub .md file is broken

### ISSUE THREAD

**Issue by sanderheilbron** [egoist/docute#87]
The link behind edit.svg (top right svg buttons) refers to an URL which does not exist:

* https://github.com/egoist/docute/blob/master/docsEADME.md
* https://github.com/egoist/docute/blob/master/docslugins.md

instead of:

* https://github.com/egoist/docute/blob/master/docs/README.md
* https://github.com/egoist/docute/blob/master/docs/plugins.md

**Comment by egoist** [comment]
Thanks for reporting the issue, fixed in `v3.0.2`
